In [7]:
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils import shuffle
import numpy as np


In [18]:
#MULTILABEL: MULTICLASS MULTIOUTPUT w/ only binary variables 
#basically just multiple random forests fitted to each output 
X, y1 = make_classification(n_samples=10, n_features=100, n_informative=30, n_classes=3, random_state=1)
y2 = shuffle(y1, random_state=1)
y3 = shuffle(y1, random_state=2)
Y = np.vstack((y1, y2, y3)).T

array([2, 1, 2, 0, 0, 0, 1, 1, 0, 2])

In [5]:
n_samples, n_features = X.shape # 10,100
n_outputs = Y.shape[1] # 3
n_classes = 3
forest = RandomForestClassifier(random_state=1)
multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
multi_target_forest.fit(X, Y)
#multi_target_forest.predict(X)
multi_target_forest.score(X,Y)

1.0

In [16]:
#CLASSIFIER CHAIN: uses correlation of different labels in prediction
from sklearn.datasets import make_multilabel_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.multioutput import ClassifierChain
X, Y = make_multilabel_classification(
   n_samples=12, n_classes=3, random_state=0
)
X_train, X_test, Y_train, Y_test = train_test_split(
   X, Y, random_state=0
)
forest = RandomForestClassifier(random_state=1)
chain = ClassifierChain(forest, order='random', random_state=0)
chain.fit(X_train, Y_train).predict(X_test)

chain.predict_proba(X_test)

array([[0.54, 0.65, 0.43],
       [0.46, 0.59, 0.4 ],
       [0.4 , 0.81, 0.22]])

In [11]:
chain.score(X_test, Y_test)

0.3333333333333333

In [12]:
#COMPARE CHAINED MODEL TO UNCHAINED
multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
multi_target_forest.fit(X_train, Y_train)
#multi_target_forest.predict(X)
multi_target_forest.score(X_test,Y_test)

0.3333333333333333

In [ ]:
#MULTICLASS MULTIOUPUT: multiple outputs that have multiple classes 

In [28]:
X, y1 = make_classification(n_samples=30, n_features=100, n_informative=30, n_classes=5, random_state=1)
y2 = shuffle(y1, random_state=1)
y3 = shuffle(y1, random_state=2)
Y = np.vstack((y1, y2, y3)).T

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(
   X, Y, random_state=0
)

In [36]:
Y_train.shape

(22, 3)

In [45]:
multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
multi_target_forest.fit(X_train, Y_train)
#multi_target_forest.predict(X)
multi_target_forest.score(X_test,Y_test)

0.0

In [40]:
multi_target_forest.predict_proba(X_test)

[array([[0.38, 0.14, 0.11, 0.2 , 0.17],
        [0.21, 0.39, 0.11, 0.15, 0.14],
        [0.21, 0.27, 0.2 , 0.15, 0.17],
        [0.23, 0.23, 0.18, 0.19, 0.17],
        [0.14, 0.28, 0.16, 0.14, 0.28],
        [0.18, 0.33, 0.19, 0.16, 0.14],
        [0.22, 0.22, 0.14, 0.28, 0.14],
        [0.29, 0.24, 0.13, 0.13, 0.21]]),
 array([[0.24, 0.17, 0.22, 0.28, 0.09],
        [0.35, 0.11, 0.19, 0.24, 0.11],
        [0.24, 0.15, 0.3 , 0.22, 0.09],
        [0.36, 0.05, 0.22, 0.26, 0.11],
        [0.4 , 0.06, 0.16, 0.24, 0.14],
        [0.42, 0.08, 0.29, 0.12, 0.09],
        [0.29, 0.15, 0.17, 0.28, 0.11],
        [0.32, 0.1 , 0.23, 0.14, 0.21]]),
 array([[0.29, 0.15, 0.17, 0.19, 0.2 ],
        [0.18, 0.35, 0.07, 0.16, 0.24],
        [0.16, 0.29, 0.09, 0.16, 0.3 ],
        [0.22, 0.3 , 0.22, 0.06, 0.2 ],
        [0.29, 0.23, 0.16, 0.18, 0.14],
        [0.21, 0.27, 0.16, 0.19, 0.17],
        [0.31, 0.16, 0.21, 0.14, 0.18],
        [0.17, 0.33, 0.2 , 0.2 , 0.1 ]])]

In [41]:
X_test.shape

(8, 100)